'use strict';

var express = require('express');
var controller = require('./order.controller');
var auth = require('../../auth/auth.service');
var router = express.Router();

router.get('/',auth.isAuthenticated(), controller.loadLatest);
router.get('/services',auth.isAuthenticated(), controller.services);
router.get('/newAndNotCompletedServices',auth.isAuthenticated(), controller.newAndNotCompletedServices);
router.get('/newAndNotCompletedServicesOlderThanTwoWeeks',auth.isAuthenticated(), controller.newAndNotCompletedServicesOlderThanTwoWeeks);
router.get('/unscheduled',auth.isAuthenticated(), controller.unscheduled);
router.get('/todotasks',auth.isAuthenticated(),controller.toDoTasks);
router.get('/shippingList',auth.isAuthenticated(),controller.shippingList);
router.get('/accessories',auth.isAuthenticated(),controller.accessories);
router.get('/comments',auth.isAuthenticated(),controller.comments);
router.get('/download/:filename', controller.fileDownload);
router.get('/:id',auth.isAuthenticated(), controller.loadOrder);
router.get('/:id/projects',auth.isAuthenticated(), controller.loadOrderProjectFields);
router.post('/:id/upload',auth.isAuthenticated(), controller.fileUpload);
router.post('/',auth.isAuthenticated(), controller.createOrder);
router.post('/:id',auth.isAuthenticated(), controller.updateOrder);
router.delete('/:id',auth.isAuthenticated(), controller.delete);
router.patch('/:id/status/:status',auth.isAuthenticated(), controller.updateStatus);
router.patch('/:id/calendar_update_date/:property/:date',auth.isAuthenticated(), controller.updateCalendarDate);
router.get('/calendar/:from/:to',auth.isAuthenticated(),controller.loadOrdersByStatusAndPeriod);
router.get('/calendar/:from/:to/otherGroupOrders',auth.isAuthenticated(),controller.loadOtherGroupOrdersByStatusAndPeriod);
router.get('/calendar/:from/:to/otherGroupServices',auth.isAuthenticated(),controller.loadOtherGroupServicesByStatusAndPeriod);
router.get('/calendar/:from/:to/orders',auth.isAuthenticated(),controller.loadOrdersByStatusAndPeriod);
router.get('/calendar/:from/:to/orders/:status',auth.isAuthenticated(),controller.loadOrdersByStatusAndPeriod);
router.get('/calendar/:from/:to/services',auth.isAuthenticated(),controller.loadServicesByStatusAndPeriod);
router.get('/calendar/:from/:to/services/:approved/:completed',auth.isAuthenticated(),controller.loadServicesByStatusAndPeriod);
module.exports = router;